manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: eiconolastes
      url-base: https://github.com/eiconoklastes
  projects:
    - name: zmk
      remote: eiconoklastes
      revision: global-quick-tap
      import: app/west.yml
  self:
    path: config
