file_format: "1"
id: haploinsufficient
name: haploinsufficient
type: shield
url: https://github.com/andrewjrae/rae-dux
requires: [pro_micro]
features:
  - keys
siblings:
  - rae_dux_left
  - rae_dux_right
