file_format: "1"
id: haplo-ins
name: haplo-ins
type: shield
url: https://github.com/eiconoklastes/haploinsufficient
requires: [pro_micro]
features:
  - keys
siblings:
  - haplo-ins_left
  - haplo-ins_right
